Vignette
Open-Systems-Pharmacology/OSPSuite.ParameterIdentification pull request #48
Opened 2023-07-11 15:10 UTC by svavil

Fixes #79
Fixes #81
Fixes #37 

The vignette details a use case and possible details of running a parameter estimation task using the package.

2023-11-27 14:32 UTC, PavelBal commented
@svavil Please resolve the conflicts.

2023-11-27 14:38 UTC, svavil commented
@PavelBal merge conflicts resolved, running and fixing tests on my machine

2023-12-11 16:12 UTC, PavelBal requested changes

2023-12-11 16:12 UTC, PavelBal commented on vignettes/user-guide.Rmd
> +Running the grid search can be a useful first step when you don't know the optimization landscape of the problem.
It would make more sense to describe grid search before "OFV grids for parameter space exploration"

2023-12-11 16:12 UTC, PavelBal commented on vignettes/user-guide.Rmd
> +If the `setStartingPoint` argument is set to `TRUE` (instead of default `FALSE`), the next optimization run will start from the best estimate across the grid.
Add more explanations. How to use `logScaleFlag` (to me it is not clear, when "a vector of logical values indicating" should be used).

How to use `margin`? (was in one of my comments to the PR introducing the grid search - I do not understand what it is and how to use it.

2023-12-11 16:12 UTC, PavelBal commented on vignettes/user-guide.Rmd
> +Around the global minimum, the objective function is expected to be convex and parabolic. We can check if we are, indeed, around a minimum (global or local) by plotting the objective function value (
Please add more explanation for the `calculateOFVProfiles` method. Examples with lower/upper. What is the output of the method, it's structure?

2023-12-11 16:13 UTC, PavelBal commented
- [ ]  https://github.com/Open-Systems-Pharmacology/OSPSuite.ParameterIdentification/issues/80
- [ ] https://github.com/Open-Systems-Pharmacology/OSPSuite.ParameterIdentification/issues/81

2024-02-19 10:28 UTC, PavelBal commented
Fixes #81

2024-02-19 10:33 UTC, PavelBal commented on R/PIConfiguration.R
>          private$.algorithmOptions <- value
Can we think of any feasible validation of user input here?

2024-02-19 10:33 UTC, PavelBal commented on R/utilities-object-functions.R
> +#' Title
@rengelke Please document this, I do not know what it does.

2024-02-19 10:47 UTC, PavelBal commented
Fixes #79

2024-02-22 16:06 UTC, PavelBal commented on R/PIConfiguration.R
> +    # #' @field simulateSteadyState Boolean representing whether the simulation
Commented out until fixed

2024-02-22 16:07 UTC, PavelBal commented on R/PIConfiguration.R
> +      #     private$printLine("Simulate to steady-state", private$.simulateSteadyState)
Comment out until fixed

2024-02-22 16:08 UTC, PavelBal commented on R/enums.R
> +AlgotitmOptions_HJKB <- enum(list(
Different algo options enums for the algos.

2024-02-22 16:09 UTC, PavelBal commented on WIP/global-agorithm-example.Rmd
> +---
This is not working because of OFV and grid search are disabled.

2024-02-22 18:40 UTC, rengelke approved these changes

2024-02-22 19:41 UTC, merged